<?php

/**
 * This file generated by Mezzio\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via mezzio-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            AuthModule\Handler\LoginHandler::class => AuthModule\Handler\LoginHandlerFactory::class,
            AuthModule\Handler\LogoutHandler::class => AuthModule\Handler\LogoutHandlerFactory::class,
            AuthModule\Handler\RegisterHandler::class => AuthModule\Handler\RegisterHandlerFactory::class,
            FrontModule\Handler\FrontHandler::class => FrontModule\Handler\FrontHandlerFactory::class,
            UserModule\Handler\ProfileHandler::class => UserModule\Handler\ProfileHandlerFactory::class,
        ],
    ],
];
